### ISSUE TITLE
Update wording for HAProxy in TCP Mode for OPNsense

### ISSUE THREAD

**Issue by SimpleTechGuy** [amidaware/trmm-docs#281]
In the Assumptions section for OPNsense in TCP Mode it says "You have a pfSense firewall." and should say "OPNsense".  

https://docs.tacticalrmm.com/unsupported_proxies/#haproxy-in-tcp-mode-opnsense

**Comment by silversword411** [comment]
We accept PRs if you know how. https://docs.tacticalrmm.com/contributing/
